---

dist: trusty
addons:
  apt:
    packages:
      - gcc-arm-none-eabi
      - libnewlib-arm-none-eabi
      - binutils-arm-none-eabi

language: c
compiler: gcc

notifications:
  email: false

script: ./.travis.sh
